/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        UpdateFeed.m
 * @copyright   (c) 2011 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "UpdateFeed.h"
#import "HostReachabilityTest.h"

@implementation UpdateFeed

@synthesize dataLoaded;
@synthesize updates;

- ( id )initWithFeedURL:( NSString * )url
{
    if( ( self = [ super init ] ) )
    {
        feedUrl = [ url copy ];
    }
    
    return self;
}

- ( void )dealloc
{
    [ feedUrl release ];
    [ updates release ];
    [ parser  release ];
    
    [ super dealloc ];
}

- ( void )loadData
{
    HostReachabilityTest * test;
    NSAutoreleasePool    * ap;
    
    ap = [ NSAutoreleasePool new ];
    
    [ [ UIApplication sharedApplication ] setNetworkActivityIndicatorVisible: YES ];
    
    test    = [ HostReachabilityTest testWithHost: @"feeds.feedburner.com" ];
    updates = [ [ NSMutableArray arrayWithCapacity: 100 ] retain ];
    
    if( test.isReachable == YES )
    {
        parser  = [ [ NSXMLParser alloc ] initWithContentsOfURL: [ NSURL URLWithString: feedUrl ] ];
        
        [ parser setDelegate: self ];
        [ parser parse ];
    }
    else
    {
        [ [ UIApplication sharedApplication ] setNetworkActivityIndicatorVisible: NO ];
    }
    
    [ ap release ];
}

- ( void )parser: ( NSXMLParser * )xml didStartElement: ( NSString * )elementName namespaceURI: ( NSString * )namespaceURI qualifiedName: ( NSString * )qName attributes: ( NSDictionary * )attributeDict
{
    ( void )xml;
    ( void )namespaceURI;
    ( void )qName;
    ( void )attributeDict;
    
    if( [ elementName isEqualToString: @"item" ] )
    {
        inItem = YES;
    }
    else if( inItem == YES && [ elementName isEqualToString: @"title" ] )
    {
        inTitle = YES;
    }
    else if( inItem == YES && [ elementName isEqualToString: @"link" ] )
    {
        inLink = YES;
        link   = [ [ NSMutableString alloc ] initWithCapacity: 100 ];
    }
    else if( inItem == YES && [ elementName isEqualToString: @"description" ] )
    {
        inDescription = YES;
        text          = [ [ NSMutableString alloc ] initWithCapacity: 500 ];
    }
}

- ( void )parser: ( NSXMLParser * )xml didEndElement: ( NSString * )elementName namespaceURI: ( NSString * )namespaceURI qualifiedName: ( NSString * )qName
{
    ( void )xml;
    ( void )namespaceURI;
    ( void )qName;
    
    if( [ elementName isEqualToString: @"item" ] )
    {
        inItem = NO;
    }
    else if( inItem == YES && [ elementName isEqualToString: @"title" ] )
    {
        inTitle = NO;
    }
    else if( inItem == YES && [ elementName isEqualToString: @"link" ] )
    {
        [ item setObject: link forKey: @"link" ];
        [ link release ];
        
        inLink = NO;
        link   = nil;
    }
    else if( inItem == YES && [ elementName isEqualToString: @"description" ] )
    {
        [ item setObject: text forKey: @"text" ];
        [ text release ];
        
        inDescription = NO;
        text          = nil;
    }
}

- ( void )parser: ( NSXMLParser * )xml foundCDATA: ( NSData * )CDATABlock
{
    NSString * content;
    NSString * title;
    NSString * description;
    NSRange    range;
    
    ( void )xml;
    
    if( inTitle == YES )
    {
        content = [ [ NSString alloc ] initWithData: CDATABlock encoding: NSUTF8StringEncoding ];
        range   = [ content rangeOfString: @" - " ];
        
        if( range.location != NSNotFound )
        {
            title       = [ content substringToIndex:   range.location ];
            description = [ content substringFromIndex: range.location + 3 ];
            item        = [ NSMutableDictionary dictionaryWithObjectsAndKeys: title, @"title", description, @"description", nil ];
        }
        
        [ updates addObject: item ];
    }
}

- ( void )parser: ( NSXMLParser * )xml foundCharacters: ( NSString * )string
{
    ( void )xml;
    
    if( inDescription == YES )
    {
        [ text appendString: string ];
    }
    else if( inLink == YES )
    {
        [ link appendString: string ];
    }
}

- ( void )parserDidEndDocument: ( NSXMLParser * )xml
{
    ( void )xml;
    
    [ [ UIApplication sharedApplication ] setNetworkActivityIndicatorVisible: NO ];
    
    dataLoaded = YES;
}

@end
